# Generated by Django 4.2.5 on 2023-09-14 05:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime
import educational_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('entrance_year', models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(0), educational_service.models.Student._max_value_current_year])),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('short_name', models.CharField(max_length=10)),
                ('foundation_date', models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='university',
            constraint=models.CheckConstraint(check=models.Q(('foundation_date__lte', django.db.models.functions.datetime.Now())), name='uni_constraint'),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_service.university', verbose_name='university'),
        ),
    ]
