# Generated by Django 4.2.5 on 2023-09-14 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='university',
            name='uni_constraint',
        ),
        migrations.AddConstraint(
            model_name='university',
            constraint=models.CheckConstraint(check=models.Q(('foundation_date__lte', datetime.date(2023, 9, 14))), name='uni_constraint'),
        ),
    ]
